version: '3.7'

services:
  api:
    build: .
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:localhost;PathPrefixStrip:/api"
      - "traefik.port=5000"

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/:/data/db
    ports:
      - 27017:27017
    labels:
      - "traefik.backend=mongo"
      - "traefik.frontend.rule=Host:mongo.localhost"
      - "traefik.port=27017"

  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - 8080:8080 # The Web UI (enabled by --api)
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  client:
    image: vtcs2304s19/blabber-client
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=80"
