version: '3.7'

services:
  server:
    build: .
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    labels:
      - "traefik.backend=server"
      - "traefik.frontend.rule=PathStrip:/api/"
      - "traefik.port=5000"
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "8080:8080" # The Web UI (enabled by --api)
      - "80:80"
    labels:
      - "traefik.backend=reverse-proxy"
      - "traefik.port=5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  client:
    image: vtcs2304s19/blabber-client
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.rule=Host:client.localhost"
      - "traefik.port=80"
