version: '3.7'

services:
  api:
    build: .
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    links:
      - mongodb
    environment:
      - DB=mongodb://mongodb:27017/blabber
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:localhost;PathPrefixStrip:/api"
      - "traefik.port=5000"

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data/:/data/db
    expose:
      - 27017
    labels:
      - "traefik.backend=mongodb"
      - "traefik.frontend.rule=Host:mongodb.localhost"
      - "traefik.port=27017"

  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - 8080:8080 # The Web UI (enabled by --api)
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  client:
    image: vtcs2304s19/blabber-client
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=80"

  tests:
    image: vtcs2304s19/blabber-api-tests:milestone3
    environment:
      SERVICE_NAME: api
      API_PORT: "5000"
    labels:
      - "traefix.backend=tests"
      - "traefik.frontend.rule=Host:localhost.tests"
